on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get full repo history
        run: git fetch --prune --unshallow --tags

      - name: Download dependencies
        shell: bash
        run: go mod download

      - name: Build
        shell: bash
        run: |
          mkdir -p bin
          go build -o bin .
          ls -la bin

      - name: Test
        shell: bash
        run: go test -race -timeout 60s ./...
